" ~/.config/vim/vimrc

" QoL Improvements

  " Enable mouse
  set mouse=a

  " Easily view text
  set wrap
  set linebreak

  " Easily switch between & update buffers
  set hidden
  set autoread

  " Undo across vim sessions
  set undofile
  let &undodir = expand('~/.local/vimundo')

  " Allow typos
  command! W w
  command! Q q
  command! Wq wq
  nnoremap q: <Nop>

  " Return to last edit position when opening files
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

  " System clipboard integration
  xnoremap +y "0y:call system('wl-copy', @0)<CR>

" Configuration

  " Allow project-local .vimrcs
  set exrc
  set secure

  " Find packages in ~/.config/vim
  set runtimepath^=~/.config/vim
  set runtimepath+=~/.config/vim/after
  set packpath^=~/.config/vim
  set packpath+=~/.config/vim/after

  " Keep viminfo in ~/.config/vim
  set viminfofile=~/.config/vim/viminfo

" Navigation

  " Line numbers
  set nu
  set rnu

  " Search
  set incsearch
  set hlsearch
  set ignorecase
  set smartcase
  set scrolloff=1

  " Jump between splits
  let mapleader = " "
  nnoremap <Leader>h <C-w>h
  nnoremap <Leader>j <C-w>j
  nnoremap <Leader>k <C-w>k
  nnoremap <Leader>l <C-w>l

  " FZF
  nnoremap <leader>f :Files<CR>
  let g:fzf_buffers_jump = 1
  let g:fzf_layout = { 'window': { 'width': 1.0, 'height': 0.2, 'yoffset': 1.0, 'border': 'top' } }
  let g:fzf_vim = {}
  let g:fzf_vim.preview_window = ['hidden']

" Code Editing

  " Tabs
  set expandtab
  set tabstop=2
  set shiftwidth=2
  set softtabstop=2
  set autoindent
  set backspace=indent,eol,start

  " Auto-extend comments
  autocmd FileType * setlocal formatoptions+=r
  autocmd FileType * setlocal formatoptions+=o

  " Insert trailing space in /* */ comments
  autocmd FileType c,cpp,go,rust,systemverilog setlocal comments=s1:/*,mf:*\ ,ex:*/

" Theme

  " Highlight code
  syntax on

  " Grab default theme
  set background=dark
  colorscheme wildcharm

  " Tweaks
  hi Statement ctermfg=218
  hi Type ctermfg=75
  hi StorageClass ctermfg=4
  hi Structure ctermfg=4
  hi Identifier ctermfg=7
  hi Function ctermfg=177
  hi Constant ctermfg=168

  " Additional per-language highlight options
  hi! link systemverilogStatement Type
  hi! link verilogStatement Type
  autocmd FileType tex highlight Statement ctermfg=75

  command! GetType echo synIDattr(synID(line("."), col("."), 1), "name")

" Code Errors (ALE)

  " Linters
  let g:ale_linters = {
  \  'c': ['gcc', 'clang'],
  \  'cpp': ['gcc', 'clang'],
  \  'go': ['gofmt', 'govet'],
  \  'rust': ['analyzer'],
  \  'systemverilog': ['verilator'],
  \  'tex': ['chktex', 'lacheck'],
  \}

  " Format fixers
  let g:ale_fixers = {
  \  '*': ['remove_trailing_lines', 'trim_whitespace'],
  "\  'go': ['gofmt'],
  "\  'rust': ['rustfmt'],
  \}

  " Additional per-language compilation options
  let g:ale_verilog_verilator_options = get(g:, 'ale_verilog_verilator_options', '') . ' --timing -Wno-MODDUP '

  " Fix format on save
  let g:ale_fix_on_save = 1

  " Don't rerun the linter until save
  let g:ale_lint_on_text_changed = 'never'
  let g:ale_lint_on_insert_leave = 0
  let g:ale_lint_on_enter = 0

  " Don't highlight error code within a line
  let g:ale_set_highlights = 0

  " Don't highlight lines within the LocList
  highlight QuickFixLine ctermbg=NONE ctermfg=NONE cterm=NONE guibg=NONE guifg=NONE gui=NONE

  " Keybinds to easily toggle errors
  command! E ALEPopulateLocList
  command! C noh | ALEReset | lclose
  command! Ec lclose

" Code Highlighting (gutentags, gutentags_plus)

  " Gutentags configuration
  let g:gutentags_project_root = ['.root', '.git']
  let g:gutentags_cache_dir = expand('~/.cache/tags')
  let g:gutentags_plus_nomap = 1
  let g:gutentags_modules = ['ctags']

  " Per-language ctags arguments
  let g:gutentags_ctags_extra_args = [
    \ '--tag-relative=yes',
    \ '--fields=+ailmnSl',
    \ '--c-kinds=+gstu',
    \ '--c++-kinds=+gstuc',
    \ '--rust-kinds=+gPMestu',
    \ '--go-kinds=+st',
    \ '--verilog-kinds=+ctvtm',
    \ '--systemverilog-kinds=+CTEeStm',
    \ '--extra=+q'
    \ ]

  " Symbol cache
  let g:project_symbol_cache = {}

  " A custom function to for additional highlighting
  function! HighlightProjectSymbols()
    let l:supported_filetypes = ['c', 'cpp', 'rust', 'go', 'systemverilog', 'verilog']
    if index(l:supported_filetypes, &filetype) == -1 | return | endif

    let l:tagfiles = tagfiles()
    if empty(l:tagfiles) | return | endif

    for l:file in l:tagfiles
      let l:resolved_file = simplify(fnamemodify(l:file, ':p'))
      if !filereadable(l:resolved_file) | continue | endif

      let l:current_mtime = getftime(l:resolved_file)

      if !has_key(g:project_symbol_cache, l:resolved_file)
        let g:project_symbol_cache[l:resolved_file] = {'mtime': 0, 'types_pattern': '', 'mods_pattern': ''}
      endif

      let l:cache = g:project_symbol_cache[l:resolved_file]

      " 1. ONLY recompute if the tags database changed on disk
      if l:current_mtime > l:cache['mtime']
        " Extract typedefs, structs, enums, etc
        " Expanded character class: [tcgTSEsue]
        "   t/T = typedefs/tasks
        "   c/C = C++ classes / SV classes
        "   g/E = enums
        "   s/S = C/C++/Rust structs
        "   u   = C/C++/Rust unions
        "   e   = Rust enums
        let l:cmd_types = "awk -F'\t' '$4 ~ /^[tcgTSEsue]$/ && $1 !~ /^[A-Z0-9_]+$/ {print $1}' " . shellescape(l:resolved_file) . " | sort -u"
        let l:types = systemlist(l:cmd_types)
        call filter(l:types, 'len(v:val) > 1 && v:val =~ "^[A-Za-z_]"')
        let l:cache['types_pattern'] = !empty(l:types) ? '\<\(' . join(l:types, '\|') . '\)\>' : ''

        " Extract SV modules
        " This can potentially be used to extract functions
        let l:cmd_mods = "awk -F'\t' '$4 == \"m\" && $1 !~ /^[A-Z0-9_]+$/ {print $1}' " . shellescape(l:resolved_file) . " | sort -u"
        let l:modules = systemlist(l:cmd_mods)
        call filter(l:modules, 'len(v:val) > 1 && v:val =~ "^[A-Za-z_]"')
        let l:cache['mods_pattern'] = !empty(l:modules) ? '\<\(' . join(l:modules, '\|') . '\)\>' : ''

        let l:cache['mtime'] = l:current_mtime
      endif

      " 2. Apply rules natively via standard syntax layer definitions
      if !empty(l:cache['types_pattern'])
        execute 'syntax match ' . 'Type' . ' "' . l:cache['types_pattern'] . '" contains=NONE display'
      endif

      if !empty(l:cache['mods_pattern'])
        execute 'syntax match ' . 'Function'. ' "' . l:cache['mods_pattern'] . '" contains=NONE display'
      endif
    endfor
  endfunction

  " Automatically highlight custom symbols
  augroup ProjectSymbolHighlighter
    autocmd!
    autocmd BufWinEnter,BufRead,BufWritePost,Syntax * call HighlightProjectSymbols()
  augroup END
