# ~/.config/bash/bashrc: executed by bash(1) for non-login shells.
# This is not located at ~/.bashrc and so must be manually added into /etc/bash.bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

if [ -f ~/.config/bash/bash_aliases ]; then
    . ~/.config/bash/bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Set custom history file location
export HISTFILE="$HOME/.config/bash/bash_history"

# Set custom less history file location
export LESSHISTFILE="$HOME/.local/state/less/history"

# Trigger logout script when exiting an interactive shell
trap '[ -f "$HOME/.config/bash/bash_logout" ] && . "$HOME/.config/bash/bash_logout"' EXIT

# \W strips the path down to just the current directory
PS1='\u:\[\e[0m\]\W\[\e[m\] \$ '

# Set up fzf
eval "$(fzf --bash)"
export FZF_DEFAULT_OPS="--bind='ctrl-k:up,ctrl-j:down'"
export FZF_COMPLETION_TRIGGER='ff'
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --no-messages --glob "!.git"'

bind '"\e[Z": "ff\t"'

# Custom function for files and paths (**<TAB>)
_fzf_compgen_path() {
  rg --files --hidden --follow --no-messages --glob "!.git" "$1"
}

# Custom function for directories only (e.g., cd **<TAB>)
_fzf_compgen_dir() {
  fdfind --type d --hidden --follow --exclude .git . "$1"
}

bind -x '"\C-f": fzf-file-widget'

export XDG_CURRENT_DESKTOP=sway

# PATH
. "$HOME/.cargo/env"
export GOPATH=$HOME/.local/share/go
export PATH=$PATH:$GOPATH/bin
